"""fantasy_average table

Revision ID: 375d6831edb7
Revises: c766dbc2b61b
Create Date: 2019-04-25 15:26:02.344485

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '375d6831edb7'
down_revision = 'c766dbc2b61b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('fantasy_average',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('date_created', sa.DateTime(), nullable=True),
    sa.Column('date_updated', sa.DateTime(), nullable=True),
    sa.Column('date', sa.Date(), nullable=True),
    sa.Column('runs', sa.Numeric(precision=4, scale=3), nullable=True),
    sa.Column('home_runs', sa.Numeric(precision=4, scale=3), nullable=True),
    sa.Column('rbi', sa.Numeric(precision=4, scale=3), nullable=True),
    sa.Column('obp', sa.Numeric(precision=4, scale=3), nullable=True),
    sa.Column('slg', sa.Numeric(precision=4, scale=3), nullable=True),
    sa.Column('wins', sa.Numeric(precision=4, scale=3), nullable=True),
    sa.Column('strikeouts', sa.Numeric(precision=4, scale=3), nullable=True),
    sa.Column('save_hold', sa.Numeric(precision=4, scale=3), nullable=True),
    sa.Column('era', sa.Numeric(precision=4, scale=3), nullable=True),
    sa.Column('whip', sa.Numeric(precision=4, scale=3), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_fantasy_average_date'), 'fantasy_average', ['date'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_fantasy_average_date'), table_name='fantasy_average')
    op.drop_table('fantasy_average')
    # ### end Alembic commands ###
