"""adding positions

Revision ID: c539c6f42bc3
Revises: 375d6831edb7
Create Date: 2019-05-04 16:47:36.457555

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c539c6f42bc3'
down_revision = '375d6831edb7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('batter_game', sa.Column('catcher', sa.Boolean(), nullable=True))
    op.add_column('batter_game', sa.Column('center', sa.Boolean(), nullable=True))
    op.add_column('batter_game', sa.Column('dh', sa.Boolean(), nullable=True))
    op.add_column('batter_game', sa.Column('first', sa.Boolean(), nullable=True))
    op.add_column('batter_game', sa.Column('left', sa.Boolean(), nullable=True))
    op.add_column('batter_game', sa.Column('outfield', sa.Boolean(), nullable=True))
    op.add_column('batter_game', sa.Column('pinch', sa.Boolean(), nullable=True))
    op.add_column('batter_game', sa.Column('pitcher', sa.Boolean(), nullable=True))
    op.add_column('batter_game', sa.Column('right', sa.Boolean(), nullable=True))
    op.add_column('batter_game', sa.Column('second', sa.Boolean(), nullable=True))
    op.add_column('batter_game', sa.Column('shortstop', sa.Boolean(), nullable=True))
    op.add_column('batter_game', sa.Column('third', sa.Boolean(), nullable=True))
    op.add_column('pitcher_game', sa.Column('relief', sa.Boolean(), nullable=True))
    op.add_column('pitcher_game', sa.Column('start', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('pitcher_game', 'start')
    op.drop_column('pitcher_game', 'relief')
    op.drop_column('batter_game', 'third')
    op.drop_column('batter_game', 'shortstop')
    op.drop_column('batter_game', 'second')
    op.drop_column('batter_game', 'right')
    op.drop_column('batter_game', 'pitcher')
    op.drop_column('batter_game', 'pinch')
    op.drop_column('batter_game', 'outfield')
    op.drop_column('batter_game', 'left')
    op.drop_column('batter_game', 'first')
    op.drop_column('batter_game', 'dh')
    op.drop_column('batter_game', 'center')
    op.drop_column('batter_game', 'catcher')
    # ### end Alembic commands ###
